apiVersion: v1
kind: Pod
metadata:
  name: tcp-echo-cloud
  namespace: cloudzone
  labels:
    app: tcp-echo-cloud
spec:
  nodeName: k8s-master
  containers:
    - name: tcp-echo-container
      image: cjimti/go-echo:latest
      imagePullPolicy: Always
      env:
        - name: TCP_PORT
          value: "2701"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      ports:
        - name: tcp-echo-port
          containerPort: 2701
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-cloud-svc
  namespace: cloudzone
  labels:
    app: tcp-echo-cloud
spec:
  selector:
    app: tcp-echo-cloud
  ports:
    - name: tcp-0
      protocol: TCP
      port: 2701
      targetPort: 2701
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-cloud
  namespace: cloudzone
spec:
  nodeName: k8s-node1
  containers:
    - name: busybox
      image: busybox:1.28
      imagePullPolicy: IfNotPresent
      args:
        - sleep
        - "12000"
